/**
 * PDF Report Export for Sentinel Medical AI.
 *
 * Strategy:
 *   - Build a clean HTML document with proper Unicode fonts (Inter / system).
 *   - Hand it to Electron's main process which renders to PDF via Chromium's
 *     native printToPDF. Chromium has full Unicode support — no garbled
 *     Cyrillic / Uzbek text.
 *   - Browser fallback (when not in Electron): open print dialog.
 */

import type { Finding } from '../types';

interface PDFReportData {
  patientId: string;
  studyDate: string;
  modality: string;
  bodyPart: string;
  reportText: string;
  doctorName: string;
  clinicName: string;
  clinicAddress: string;
  signedAt?: string;
  findings: Finding[];
  dicomImageBase64?: string;
  language?: 'ru' | 'uz' | 'en';
}

// Translations for static PDF labels
const LABELS = {
  ru: {
    patientId: 'ID Пациента',
    studyDate: 'Дата исследования',
    modality: 'Модальность',
    bodyPart: 'Область',
    aiFindings: 'РЕЗУЛЬТАТЫ ИИ-АНАЛИЗА',
    confidence: 'достоверность',
    location: 'локализация',
    notSigned: '[НЕ ПОДПИСАНО]',
    signed: 'ПОДПИСАНО',
    radiologist: 'Врач-рентгенолог',
    footer:
      'Создано системой Sentinel Medical AI (siaa.uz) — результаты ИИ носят рекомендательный характер и требуют подтверждения врачом.',
  },
  uz: {
    patientId: 'Bemor ID',
    studyDate: 'Tekshiruv sanasi',
    modality: 'Modallik',
    bodyPart: 'Soha',
    aiFindings: 'AI-TAHLIL NATIJALARI',
    confidence: 'ishonchlilik',
    location: 'joylashuv',
    notSigned: '[IMZOLANMAGAN]',
    signed: 'IMZOLANGAN',
    radiologist: 'Rentgenolog shifokor',
    footer:
      'Sentinel Medical AI (siaa.uz) tomonidan yaratilgan — AI natijalari tavsiya xarakteriga ega va shifokor tasdig\'ini talab qiladi.',
  },
  en: {
    patientId: 'Patient ID',
    studyDate: 'Study Date',
    modality: 'Modality',
    bodyPart: 'Body Part',
    aiFindings: 'AI ANALYSIS FINDINGS',
    confidence: 'confidence',
    location: 'location',
    notSigned: '[NOT SIGNED]',
    signed: 'SIGNED',
    radiologist: 'Radiologist',
    footer:
      'Generated by Sentinel Medical AI (siaa.uz) — AI results are advisory and require physician confirmation.',
  },
} as const;

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function buildSinglePagePDFHTML(data: PDFReportData): string {
  const lang = data.language || 'ru';
  const L = LABELS[lang];
  const reportLines = data.reportText.split('\n');

  // Format report — detect headers (uppercase ending with ':')
  const reportHTML = reportLines
    .map((rawLine) => {
      const line = rawLine.trim();
      if (!line) return '<div class="spacer"></div>';
      const isHeader =
        line === line.toUpperCase() && line.length > 3 && line.endsWith(':');
      if (isHeader) {
        return `<h3 class="section-header">${escapeHtml(line)}</h3>`;
      }
      // Separator lines like "---"
      if (/^-{3,}$/.test(line)) {
        return '<hr class="report-hr"/>';
      }
      return `<p class="report-para">${escapeHtml(line)}</p>`;
    })
    .join('\n');

  // Findings list
  const findingsHTML =
    data.findings && data.findings.length > 0
      ? `
      <div class="findings-block">
        <h2 class="findings-title">${L.aiFindings}</h2>
        <table class="findings-table">
          ${data.findings
            .map((f) => {
              const conf = Math.round(f.confidence * 100);
              const sevColor =
                conf >= 80 ? '#dc2626' : conf >= 50 ? '#f59e0b' : '#84cc16';
              return `
                <tr>
                  <td class="finding-name">${escapeHtml(f.className)}</td>
                  <td class="finding-bar-cell">
                    <div class="bar-bg">
                      <div class="bar-fill" style="width:${conf}%;background:${sevColor};"></div>
                    </div>
                  </td>
                  <td class="finding-conf">${conf}%</td>
                  <td class="finding-loc">${escapeHtml(f.location || '')}</td>
                </tr>`;
            })
            .join('')}
        </table>
      </div>`
      : '';

  const sigBlock = data.signedAt
    ? `<div class="sig signed">
         <div class="sig-line"></div>
         <div class="sig-name">${escapeHtml(data.doctorName)}</div>
         <div class="sig-status">✓ ${L.signed}: ${escapeHtml(data.signedAt)}</div>
       </div>`
    : `<div class="sig">
         <div class="sig-line"></div>
         <div class="sig-name">${escapeHtml(data.doctorName)}</div>
         <div class="sig-status not-signed">${L.notSigned}</div>
       </div>`;

  return `
    <header class="letterhead">
      <div class="lh-left">
        <div class="brand">SENTINEL MEDICAL AI</div>
        <div class="clinic">${escapeHtml(data.clinicName || 'SIA Medical AI')}</div>
        <div class="clinic-addr">${escapeHtml(data.clinicAddress || 'Tashkent, Uzbekistan')} · siaa.uz</div>
      </div>
      <div class="lh-right">
        <div>${L.patientId}: <strong>${escapeHtml(data.patientId)}</strong></div>
        <div>${L.studyDate}: <strong>${escapeHtml(data.studyDate)}</strong></div>
        <div>${escapeHtml(data.modality)} — ${escapeHtml(data.bodyPart)}</div>
      </div>
    </header>

    <section class="patient-box">
      <div class="pi"><span class="pi-k">${L.patientId}:</span> <span class="pi-v">${escapeHtml(data.patientId)}</span></div>
      <div class="pi"><span class="pi-k">${L.studyDate}:</span> <span class="pi-v">${escapeHtml(data.studyDate)}</span></div>
      <div class="pi"><span class="pi-k">${L.modality}:</span> <span class="pi-v">${escapeHtml(data.modality)}</span></div>
      <div class="pi"><span class="pi-k">${L.bodyPart}:</span> <span class="pi-v">${escapeHtml(data.bodyPart)}</span></div>
    </section>

    ${findingsHTML}

    <section class="report-body">
      ${reportHTML}
    </section>

    ${sigBlock}

    <footer class="page-footer">${L.footer}</footer>
  `;
}

function wrapInDocument(bodyContent: string): string {
  // Self-contained HTML doc with embedded CSS.
  // Uses system fonts that have full Cyrillic + Uzbek Latin coverage on
  // every modern OS (San Francisco on macOS, Segoe UI on Windows).
  return `<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8" />
<title>Sentinel Report</title>
<style>
  * { box-sizing: border-box; }
  html, body {
    margin: 0;
    padding: 0;
    font-family: -apple-system, "Segoe UI", "Helvetica Neue", "Liberation Sans", "DejaVu Sans", Arial, sans-serif;
    color: #0f172a;
    font-size: 10pt;
    line-height: 1.45;
  }
  body { padding: 0 18mm; }

  .letterhead {
    background: #0f172a;
    color: #fff;
    margin: -8mm -18mm 6mm -18mm;
    padding: 8mm 18mm;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  .brand { font-size: 14pt; font-weight: 700; letter-spacing: 0.5px; }
  .clinic { font-size: 9pt; opacity: 0.95; margin-top: 2pt; }
  .clinic-addr { font-size: 8pt; opacity: 0.8; }
  .lh-right { text-align: right; font-size: 8.5pt; line-height: 1.5; }

  .patient-box {
    border: 1px solid #cbd5e1;
    border-radius: 4px;
    padding: 5pt 8pt;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 4pt 16pt;
    margin-bottom: 8pt;
    font-size: 9pt;
  }
  .pi-k { color: #475569; font-weight: 600; }
  .pi-v { color: #0f172a; }

  .findings-block { margin: 6pt 0 10pt 0; }
  .findings-title {
    font-size: 10pt;
    font-weight: 700;
    color: #0f172a;
    margin: 0 0 4pt 0;
    padding-bottom: 2pt;
    border-bottom: 2px solid #0f172a;
    letter-spacing: 0.3px;
  }
  .findings-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 9pt;
  }
  .findings-table tr { border-bottom: 1px solid #f1f5f9; }
  .findings-table td { padding: 3pt 4pt; vertical-align: middle; }
  .finding-name { font-weight: 600; width: 28%; }
  .finding-bar-cell { width: 35%; }
  .bar-bg { background: #e2e8f0; height: 5pt; border-radius: 2pt; overflow: hidden; }
  .bar-fill { height: 100%; }
  .finding-conf { width: 10%; text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; }
  .finding-loc { width: 27%; color: #64748b; font-size: 8.5pt; }

  .report-body { margin-top: 6pt; }
  .section-header {
    font-size: 10pt;
    font-weight: 700;
    color: #0f172a;
    margin: 8pt 0 2pt 0;
    letter-spacing: 0.3px;
  }
  .report-para { margin: 2pt 0; text-align: justify; }
  .report-hr { border: none; border-top: 1px dashed #cbd5e1; margin: 6pt 0; }
  .spacer { height: 3pt; }

  .sig { margin-top: 12pt; }
  .sig-line { border-top: 1px solid #475569; width: 60mm; margin-bottom: 3pt; }
  .sig-name { font-weight: 700; font-size: 10pt; }
  .sig-status { color: #64748b; font-size: 8.5pt; margin-top: 1pt; }
  .sig.signed .sig-status { color: #16a34a; font-weight: 600; }
  .sig-status.not-signed { color: #94a3b8; }

  .page-footer {
    position: fixed;
    bottom: 4mm;
    left: 18mm;
    right: 18mm;
    font-size: 7pt;
    color: #94a3b8;
    text-align: center;
    border-top: 1px solid #e2e8f0;
    padding-top: 2pt;
  }

  /* Multi-language separator */
  .lang-page-break { page-break-after: always; }
  .lang-marker {
    background: #1e293b;
    color: #fff;
    display: inline-block;
    padding: 2pt 8pt;
    border-radius: 3pt;
    font-size: 8pt;
    font-weight: 700;
    margin-bottom: 4pt;
    letter-spacing: 0.5px;
  }

  @page { size: A4; margin: 8mm 0; }
  @media print {
    body { padding: 0 18mm; }
  }
</style>
</head>
<body>
${bodyContent}
</body>
</html>`;
}

/**
 * Build the full HTML for a single-language PDF.
 */
export function buildPDFHTML(data: PDFReportData): string {
  return wrapInDocument(buildSinglePagePDFHTML(data));
}

/**
 * Build the full HTML for a multi-language PDF (RU + UZ + EN, one section each).
 * The `reportTextByLang` map provides the report text in each language.
 */
export function buildMultiLanguagePDFHTML(
  base: Omit<PDFReportData, 'reportText' | 'language'>,
  reportTextByLang: { ru?: string; uz?: string; en?: string },
): string {
  const langs: Array<'ru' | 'uz' | 'en'> = ['ru', 'uz', 'en'];
  const langLabels = { ru: 'РУССКИЙ', uz: "O'ZBEK", en: 'ENGLISH' };

  const sections = langs
    .map((lang, idx) => {
      const text = reportTextByLang[lang];
      if (!text) return '';
      const bodyHtml = buildSinglePagePDFHTML({
        ...base,
        reportText: text,
        language: lang,
      });
      const breakClass =
        idx < langs.filter((l) => reportTextByLang[l]).length - 1
          ? 'lang-page-break'
          : '';
      return `
        <div class="lang-section ${breakClass}">
          <div style="text-align:center;margin:4pt 0;">
            <span class="lang-marker">${langLabels[lang]}</span>
          </div>
          ${bodyHtml}
        </div>`;
    })
    .filter(Boolean)
    .join('\n');

  return wrapInDocument(sections);
}

/**
 * Trigger the PDF download. In Electron, uses native printToPDF (full Unicode).
 * In a normal browser, opens the print dialog with the styled HTML.
 */
export async function downloadPDF(
  data: PDFReportData,
  filename?: string,
): Promise<{ success: boolean; filePath?: string; canceled?: boolean }> {
  const html = buildPDFHTML(data);
  const safeName =
    filename ||
    `sentinel_${data.patientId}_${data.studyDate}_${data.language || 'ru'}.pdf`;

  // Electron path — native PDF rendering with full Cyrillic/Uzbek support
  const electronAPI = (window as any).electronAPI;
  if (electronAPI?.exportPDF) {
    return await electronAPI.exportPDF(html, safeName);
  }

  // Browser fallback — open print preview
  const w = window.open('', '_blank');
  if (!w) return { success: false };
  w.document.write(html);
  w.document.close();
  setTimeout(() => {
    w.focus();
    w.print();
  }, 400);
  return { success: true };
}

/**
 * Download a PDF containing all 3 language reports.
 */
export async function downloadMultiLanguagePDF(
  base: Omit<PDFReportData, 'reportText' | 'language'>,
  reportTextByLang: { ru?: string; uz?: string; en?: string },
  filename?: string,
): Promise<{ success: boolean; filePath?: string; canceled?: boolean }> {
  const html = buildMultiLanguagePDFHTML(base, reportTextByLang);
  const safeName =
    filename || `sentinel_${base.patientId}_${base.studyDate}_multilang.pdf`;

  const electronAPI = (window as any).electronAPI;
  if (electronAPI?.exportPDF) {
    return await electronAPI.exportPDF(html, safeName);
  }

  const w = window.open('', '_blank');
  if (!w) return { success: false };
  w.document.write(html);
  w.document.close();
  setTimeout(() => {
    w.focus();
    w.print();
  }, 400);
  return { success: true };
}
